export const RECEIVE_DETAILINFO = 'receive_detailInfo'
export const RECEIVE_VIDEOURL = 'receive_videourl' 
export const RECEIVE_ALLDETAILINFO = 'receive_alldetailinfo'
export const RECEIVE_DanMu = 'receive_danmu' 
export const RECEIVE_RECOMMEND = 'receive_recommend' 